version: "3.3"

services:

  traefik:
    image: "traefik:v2.1.4"
    container_name: "traefik"
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.20"
          memory: "64M"
        reservations:
          cpus: "0.10"
          memory: "32M"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  helloworld:
    image: tutum/hello-world:latest
    container_name: webapp_helloworld
    networks:
     - traefik-public
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.10"
          memory: "64M"
        reservations:
          cpus: "0.07"
          memory: "32M"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.helloworld.rule=Host(`hello.emma.local`)"
        - "traefik.http.routers.helloworld.entrypoints=web"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true

